# Generated by Django 3.1.3 on 2020-12-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=150)),
                ('creationdate', models.DateTimeField()),
                ('updatedate', models.DateTimeField()),
                ('text', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('organism', models.ForeignKey(default='n/a', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainpage.organism')),
            ],
        ),
    ]
