# Generated by Django 3.1.3 on 2020-12-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='organism',
            field=models.CharField(max_length=150),
        ),
    ]
