# Generated by Django 3.1.3 on 2020-12-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
