# Generated by Django 3.1.3 on 2020-12-04 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updatedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
