# Generated by Django 3.1.3 on 2020-12-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_post_updatedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updatedby',
        ),
    ]
